name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: npm install
      - run: npm run build
        env:
          NODE_ENV: production
          VITE_UNSPLASH_ACCESS_KEY: ${{ secrets.VITE_UNSPLASH_ACCESS_KEY }}
      - name: List build directory contents # Debugging step
        run: ls -lah build/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
